-- ============================================================
-- Migration 0007: ai_classifications table
-- ============================================================
-- Every AI inference result is stored here for auditability,
-- retraining, and confidence-gated automation.
-- One row per (message OR conversation) per classification run.
-- Duplicate classifications on the same message are prevented
-- by the partial unique index in 0009_indexes.sql.
-- ============================================================

CREATE TABLE ai_classifications (
    -- Identity
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Scope — exactly one of these must be set
    lead_id             UUID        NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    -- Set when classifying a single inbound message
    message_id          UUID        REFERENCES messages(id) ON DELETE SET NULL,
    -- Set when re-classifying a full conversation
    conversation_id     UUID        REFERENCES conversations(id) ON DELETE SET NULL,

    -- Classification output
    intent              ai_intent   NOT NULL,
    -- Confidence 0.0–1.0
    confidence          NUMERIC(4,3) NOT NULL
                            CHECK (confidence BETWEEN 0 AND 1),
    -- Sentiment: positive, neutral, negative
    sentiment           TEXT,
    sentiment_score     NUMERIC(4,3)
                            CHECK (sentiment_score IS NULL OR sentiment_score BETWEEN -1 AND 1),

    -- Lead qualification score 0–100 (NULL until enough context exists)
    qualification_score SMALLINT    CHECK (qualification_score IS NULL OR qualification_score BETWEEN 0 AND 100),

    -- Summary generated by the AI (used in dashboard card)
    summary             TEXT,

    -- Suggested next action for agent or AI bot
    -- e.g. "Send pricing brochure", "Schedule demo", "Escalate to human"
    suggested_action    TEXT,

    -- Whether automation acted on this classification
    action_taken        BOOLEAN     NOT NULL DEFAULT FALSE,
    action_taken_at     TIMESTAMPTZ,
    action_details      JSONB       NOT NULL DEFAULT '{}',

    -- Model metadata
    model_provider      TEXT        NOT NULL,  -- 'gemini' | 'openai'
    model_name          TEXT        NOT NULL,  -- 'gemini-1.5-pro' | 'gpt-4o'
    model_version       TEXT,
    -- Input/output token counts for cost tracking
    input_tokens        INTEGER,
    output_tokens       INTEGER,
    -- Latency in milliseconds
    latency_ms          INTEGER,

    -- Raw prompts + completion for debugging (excluded from standard selects)
    raw_prompt          TEXT,
    raw_completion      TEXT,

    -- Audit timestamps
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- --------------------------------------------------------
    -- Constraints
    -- --------------------------------------------------------
    -- Exactly one scope must be set
    CONSTRAINT chk_classification_scope
        CHECK (
            (message_id IS NOT NULL AND conversation_id IS NULL) OR
            (message_id IS NULL AND conversation_id IS NOT NULL)
        ),

    CONSTRAINT chk_sentiment_value
        CHECK (sentiment IS NULL OR sentiment IN ('positive', 'neutral', 'negative'))
);

CREATE TRIGGER trg_ai_classifications_updated_at
    BEFORE UPDATE ON ai_classifications
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE  ai_classifications                    IS 'Every AI inference result — immutable audit log';
COMMENT ON COLUMN ai_classifications.confidence         IS 'Model confidence 0.0–1.0';
COMMENT ON COLUMN ai_classifications.sentiment_score    IS '-1.0 (negative) to +1.0 (positive)';
COMMENT ON COLUMN ai_classifications.qualification_score IS 'Lead quality 0–100; NULL until enough context exists';
COMMENT ON COLUMN ai_classifications.suggested_action   IS 'AI-recommended next step for agent or bot';
COMMENT ON COLUMN ai_classifications.input_tokens       IS 'Token count for cost attribution';
COMMENT ON COLUMN ai_classifications.raw_prompt         IS 'Full prompt sent to model — stored for debugging only';
COMMENT ON COLUMN ai_classifications.raw_completion     IS 'Raw model completion — stored for debugging only';
